//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Adriel Shit/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""0ea0c1bb-f617-4d09-9b40-2e806a5f5357"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""3161f098-efd6-4bcc-a746-43b4e9bf01bf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraMovement"",
                    ""type"": ""Value"",
                    ""id"": ""28dbb62e-1b6c-4d60-9561-d64c76f6c697"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""a2475469-cabd-4ccb-860d-ef3b7d93f914"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XAction"",
                    ""type"": ""Button"",
                    ""id"": ""1eeafc16-8b36-4311-999d-c8d80beb5a36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""YAction"",
                    ""type"": ""Button"",
                    ""id"": ""01e7e3c8-af71-4a4d-8560-9b8c930758ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AAction"",
                    ""type"": ""Button"",
                    ""id"": ""ddae1291-6b32-4b4c-a8a1-6798ba7069dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RBAction"",
                    ""type"": ""Button"",
                    ""id"": ""a1a2df4e-15b8-4482-b28c-1020ae0565b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LBAction"",
                    ""type"": ""Button"",
                    ""id"": ""253b4aa2-6a9e-4ade-924d-fa3dd311edba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LTAction"",
                    ""type"": ""Button"",
                    ""id"": ""908a9dd3-3b10-4d2f-860b-6ed1bad5ec05"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RTAction"",
                    ""type"": ""Button"",
                    ""id"": ""91853cbd-2601-494a-8c8a-1f5eaff863e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartAction"",
                    ""type"": ""Button"",
                    ""id"": ""eb5c4093-cb63-4f56-a72d-a85848e06238"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dpad"",
                    ""type"": ""Value"",
                    ""id"": ""ad6be0c3-ba5c-4c65-9d00-edb82a8dd312"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectAction"",
                    ""type"": ""Button"",
                    ""id"": ""225a8260-24a8-4810-98a2-91c58202a301"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UIMovement"",
                    ""type"": ""Value"",
                    ""id"": ""44365e7f-cef3-4c8a-a857-6c94df80014f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8647ba13-5c5f-43ff-8b9c-7ca0ca8bca75"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2023c1c3-cce1-4ede-a4c8-66f84740f8f2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8df827a5-4d33-42a9-ab17-b39bac184059"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""aca6dcb7-1a72-4131-96bc-43f7f2e3acfe"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5f8a376c-31b7-497f-a51a-674bc6db9fca"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""630465e8-3217-483b-a140-4287c3b0cccb"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f9761bf-70b9-4675-a581-1028e7b0ab1a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7601b8e-9489-4a21-a7e1-c787c8bbb71b"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11234563-3993-4f02-aa3a-633753ee997c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a074dae0-10c8-40b4-a621-b4974dd758da"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""YAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e4bda21-c3dc-41cf-86ff-dbb8b158181e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97659666-10a4-4987-9706-79157e146aed"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RBAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba6c7806-5c37-4070-adec-f36e591d0dc1"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LBAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcfe0a86-a91d-49ca-ab71-0f8794f85780"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LTAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9408f102-7187-4021-898f-fbb6d3b31884"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bbb5a43-4ab1-417f-9a3e-97f41f0d40e0"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7d681de4-8204-4fef-8acd-f5ca45b17cc8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dpad"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0c01ac1a-e98e-4ece-8bfd-7f6a0163f9e2"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cb9582ff-1f11-41b1-b6ea-fab7801ff413"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e7c5555b-20e3-4ec3-9560-5293d937a15d"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""170de17d-cb24-4d25-a70b-7b6810dc88cc"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dpad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5974a059-a131-418e-aa89-0f84abe9be1f"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""19e21432-fd78-4f2e-a95d-1b47dde631a5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIMovement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b312bd95-93de-4b9b-9df6-723c45d53c63"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""662295c2-4a3d-4e32-8a62-861ac1846d21"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9ea66646-ba41-4163-a161-6750308c7ff5"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""57cedfbd-829d-4025-a60f-332547195535"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""149ee81a-5ce1-4d61-8dcd-cd27faf97de8"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UIMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b56e44d-6a10-42e4-bc14-5cc72b5e046b"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_CameraMovement = m_Player.FindAction("CameraMovement", throwIfNotFound: true);
        m_Player_Dash = m_Player.FindAction("Dash", throwIfNotFound: true);
        m_Player_XAction = m_Player.FindAction("XAction", throwIfNotFound: true);
        m_Player_YAction = m_Player.FindAction("YAction", throwIfNotFound: true);
        m_Player_AAction = m_Player.FindAction("AAction", throwIfNotFound: true);
        m_Player_RBAction = m_Player.FindAction("RBAction", throwIfNotFound: true);
        m_Player_LBAction = m_Player.FindAction("LBAction", throwIfNotFound: true);
        m_Player_LTAction = m_Player.FindAction("LTAction", throwIfNotFound: true);
        m_Player_RTAction = m_Player.FindAction("RTAction", throwIfNotFound: true);
        m_Player_StartAction = m_Player.FindAction("StartAction", throwIfNotFound: true);
        m_Player_Dpad = m_Player.FindAction("Dpad", throwIfNotFound: true);
        m_Player_SelectAction = m_Player.FindAction("SelectAction", throwIfNotFound: true);
        m_Player_UIMovement = m_Player.FindAction("UIMovement", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_CameraMovement;
    private readonly InputAction m_Player_Dash;
    private readonly InputAction m_Player_XAction;
    private readonly InputAction m_Player_YAction;
    private readonly InputAction m_Player_AAction;
    private readonly InputAction m_Player_RBAction;
    private readonly InputAction m_Player_LBAction;
    private readonly InputAction m_Player_LTAction;
    private readonly InputAction m_Player_RTAction;
    private readonly InputAction m_Player_StartAction;
    private readonly InputAction m_Player_Dpad;
    private readonly InputAction m_Player_SelectAction;
    private readonly InputAction m_Player_UIMovement;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @CameraMovement => m_Wrapper.m_Player_CameraMovement;
        public InputAction @Dash => m_Wrapper.m_Player_Dash;
        public InputAction @XAction => m_Wrapper.m_Player_XAction;
        public InputAction @YAction => m_Wrapper.m_Player_YAction;
        public InputAction @AAction => m_Wrapper.m_Player_AAction;
        public InputAction @RBAction => m_Wrapper.m_Player_RBAction;
        public InputAction @LBAction => m_Wrapper.m_Player_LBAction;
        public InputAction @LTAction => m_Wrapper.m_Player_LTAction;
        public InputAction @RTAction => m_Wrapper.m_Player_RTAction;
        public InputAction @StartAction => m_Wrapper.m_Player_StartAction;
        public InputAction @Dpad => m_Wrapper.m_Player_Dpad;
        public InputAction @SelectAction => m_Wrapper.m_Player_SelectAction;
        public InputAction @UIMovement => m_Wrapper.m_Player_UIMovement;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @CameraMovement.started += instance.OnCameraMovement;
            @CameraMovement.performed += instance.OnCameraMovement;
            @CameraMovement.canceled += instance.OnCameraMovement;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @XAction.started += instance.OnXAction;
            @XAction.performed += instance.OnXAction;
            @XAction.canceled += instance.OnXAction;
            @YAction.started += instance.OnYAction;
            @YAction.performed += instance.OnYAction;
            @YAction.canceled += instance.OnYAction;
            @AAction.started += instance.OnAAction;
            @AAction.performed += instance.OnAAction;
            @AAction.canceled += instance.OnAAction;
            @RBAction.started += instance.OnRBAction;
            @RBAction.performed += instance.OnRBAction;
            @RBAction.canceled += instance.OnRBAction;
            @LBAction.started += instance.OnLBAction;
            @LBAction.performed += instance.OnLBAction;
            @LBAction.canceled += instance.OnLBAction;
            @LTAction.started += instance.OnLTAction;
            @LTAction.performed += instance.OnLTAction;
            @LTAction.canceled += instance.OnLTAction;
            @RTAction.started += instance.OnRTAction;
            @RTAction.performed += instance.OnRTAction;
            @RTAction.canceled += instance.OnRTAction;
            @StartAction.started += instance.OnStartAction;
            @StartAction.performed += instance.OnStartAction;
            @StartAction.canceled += instance.OnStartAction;
            @Dpad.started += instance.OnDpad;
            @Dpad.performed += instance.OnDpad;
            @Dpad.canceled += instance.OnDpad;
            @SelectAction.started += instance.OnSelectAction;
            @SelectAction.performed += instance.OnSelectAction;
            @SelectAction.canceled += instance.OnSelectAction;
            @UIMovement.started += instance.OnUIMovement;
            @UIMovement.performed += instance.OnUIMovement;
            @UIMovement.canceled += instance.OnUIMovement;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @CameraMovement.started -= instance.OnCameraMovement;
            @CameraMovement.performed -= instance.OnCameraMovement;
            @CameraMovement.canceled -= instance.OnCameraMovement;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @XAction.started -= instance.OnXAction;
            @XAction.performed -= instance.OnXAction;
            @XAction.canceled -= instance.OnXAction;
            @YAction.started -= instance.OnYAction;
            @YAction.performed -= instance.OnYAction;
            @YAction.canceled -= instance.OnYAction;
            @AAction.started -= instance.OnAAction;
            @AAction.performed -= instance.OnAAction;
            @AAction.canceled -= instance.OnAAction;
            @RBAction.started -= instance.OnRBAction;
            @RBAction.performed -= instance.OnRBAction;
            @RBAction.canceled -= instance.OnRBAction;
            @LBAction.started -= instance.OnLBAction;
            @LBAction.performed -= instance.OnLBAction;
            @LBAction.canceled -= instance.OnLBAction;
            @LTAction.started -= instance.OnLTAction;
            @LTAction.performed -= instance.OnLTAction;
            @LTAction.canceled -= instance.OnLTAction;
            @RTAction.started -= instance.OnRTAction;
            @RTAction.performed -= instance.OnRTAction;
            @RTAction.canceled -= instance.OnRTAction;
            @StartAction.started -= instance.OnStartAction;
            @StartAction.performed -= instance.OnStartAction;
            @StartAction.canceled -= instance.OnStartAction;
            @Dpad.started -= instance.OnDpad;
            @Dpad.performed -= instance.OnDpad;
            @Dpad.canceled -= instance.OnDpad;
            @SelectAction.started -= instance.OnSelectAction;
            @SelectAction.performed -= instance.OnSelectAction;
            @SelectAction.canceled -= instance.OnSelectAction;
            @UIMovement.started -= instance.OnUIMovement;
            @UIMovement.performed -= instance.OnUIMovement;
            @UIMovement.canceled -= instance.OnUIMovement;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCameraMovement(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnXAction(InputAction.CallbackContext context);
        void OnYAction(InputAction.CallbackContext context);
        void OnAAction(InputAction.CallbackContext context);
        void OnRBAction(InputAction.CallbackContext context);
        void OnLBAction(InputAction.CallbackContext context);
        void OnLTAction(InputAction.CallbackContext context);
        void OnRTAction(InputAction.CallbackContext context);
        void OnStartAction(InputAction.CallbackContext context);
        void OnDpad(InputAction.CallbackContext context);
        void OnSelectAction(InputAction.CallbackContext context);
        void OnUIMovement(InputAction.CallbackContext context);
    }
}
